### ISSUE TITLE
Update controller-runtime to v0.15.0

### ISSUE THREAD

**Issue by blkperl** [cisco-open/operator-tools#159]
## Problem Statement

controller-runtime was recently released with support for k8s 1.27.x

https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0

## Proposed Solution

Update the go.mod and update code for the backward breaking changes

## Alternatives Considered

None

## Additional Context

None

**Comment by pepov** [comment]
fixed in https://github.com/cisco-open/operator-tools/pull/158
